### ISSUE TITLE
"Report.get_json_report_object()" is broken

### ISSUE THREAD

**Issue by UrmelAusDemEis** [mass-project/mass_api_client#46]
self.json_report_objects does not exist

**Comment by fabian-rump** [comment]
There exists get_json_report_object:
https://github.com/mass-project/mass_api_client/blob/master/mass_api_client/resources/report.py#L35

@Silberschleier Can we add a corresponding property so that the report object are accessible like self.json_report_objects['xyz']?

**Comment by Silberschleier** [comment]
I quickly added a such a property in #48. It's not ideal though as it may also download unnecessary report objects.
So I'm still thinking about something more elegant.

**Comment by fabian-rump** [comment]
Solved by #48.
