### ISSUE TITLE
Sample.query is missing a tags__contains filter

### ISSUE THREAD

**Issue by norcuni** [mass-project/mass_api_client#63]
Hey there, 

the only way to query samples atm is tags__all. This does not make much sense since this requires a user to know all the tags of sample in order to retrieve it by this filter. Imho it would be more meaningful to have a filter tags__contains that allows retrieving samples that contain a specific tag.

edit:
Some testing revealed that tags__all actually checks if a tag is contained. This means that the only issue is a poorly chosen name. Since that is not as important for me, this issue might just be closed or deleted:)

Best regards
Jonathan

**Comment by fabian-rump** [comment]
Indeed this name is confusing, but we decided to stick with the mongoengine query names for consistency. However this should clearly be documented. Closing this in favor of #72.
