### ISSUE TITLE
ScheduledAnalysis.create_report does not take additional_metadata

### ISSUE THREAD

**Issue by tbehner** [mass-project/mass_api_client#70]

**Comment by tbehner** [comment]
Are you sure this is closed? [The corresponding line](https://github.com/mass-project/mass_api_client/blob/6838c4852e967d8b918e40488ecdf4ad92cc6a19/mass_api_client/resources/scheduled_analysis.py#L26) is still missing the parameter.
Did I forget or miss something?
Just in case, I updated the branch fix-70 to the current master and can make a pull request.

**Comment by Silberschleier** [comment]
Yes, you are right. Not quite sure why we closed this last week.

**Comment by tbehner** [comment]
Ok, I created a pull request and assigned you for the review.
