### ISSUE TITLE
Prepare for publishing with pip

### ISSUE THREAD

**Issue by fabian-rump** [mass-project/mass_api_client#73]
- Check requirements for publishing (do we need an account? etc.)
- Change setup.py where required

**Comment by fabian-rump** [comment]
Also important: We should agree on a workflow for publishing new versions (possibly automated?)

**Comment by norcuni** [comment]
Just a small reminder: please remember to integrate a version number that is somehow increased automatically (checkout setup tools_scm for that!). Otherwise "pip install ... --upgrade" won't work.
